name: 'tinydeskcharts'
version: '1.0'
config-version: 2

profile: 'tinydeskcharts_profile'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  tinydeskcharts:
    +materialized: table
