# .github/workflows/cronjob.yml
name: ingestion_cron

on:
  schedule:
    - cron: "30 12 * * *"  # Executa todos os dias às 03:00 UTC
  workflow_dispatch:      # Permite rodar manualmente também

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create .env file
        run: |
          echo "${{ secrets.DOTENV_FILE }}" > .env

      - name: Run script
        run: |
          python ingestion/main.py
